version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestAssetUpdateProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.testassetupdate.integrations:testGitProject
  packages:
  - name: TestAssetUpdateProject
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.2032
